### ISSUE TITLE
What is the futility binary in scripts/chromeos?

### ISSUE THREAD

**Issue by IzzySoft** [anasfanani/magisk-autoboot#1]
In `scripts/chromeos` there's a binary called `futility`, but it's not mentioned in the readme (or elsewhere). Could you please outline what it is and where it comes from, especially where its source code can be investigated? Thanks in advance!

**Comment by anasfanani** [comment]
This only for ChromeOS, https://github.com/anasfanani/magisk-autoboot/blob/8ff5fe8a05cf3a655f2dcd14a6e6593703468191/scripts/util_functions.sh#L448

Its from this https://github.com/topjohnwu/Magisk/blob/062e498bddbe51b4e5b4395a40a6b8a75565b90e/scripts/util_functions.sh#L447

**Comment by IzzySoft** [comment]
Thanks! At the linked place I see it is used. Is it itself FOSS (and is there a link to the code), or is it proprietary (and thus no link to its code available)?

**Comment by anasfanani** [comment]
> Thanks! At the linked place I see it is used. Is it itself FOSS (and is there a link to the code), or is it proprietary (and thus no link to its code available)?

I'm not sure about this, here are some references I got.

```
$ file futility
futility: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, BuildID[md5/uuid]=2a634a4b19ea852faf70891a42a7cb4b, stripped
```

https://github.com/topjohnwu/Magisk/blob/master/tools/futility

https://chromium.googlesource.com/chromiumos/platform/vboot/+/0e5f54d79158f216edeb42bfe9c5cd6d35dc6e0d/Makefile#625

https://github.com/coreboot/vboot/blob/main/Android.mk#L121

https://www.google.com/search?q=%22futility%2Ffutility.c%22

**Comment by IzzySoft** [comment]
Thanks! The source seems to [be available](https://chromium.googlesource.com/chromiumos/platform/vboot/+/0e5f54d79158f216edeb42bfe9c5cd6d35dc6e0d/futility/futility.c). It says "Use of this source code is governed by a BSD-style license that can be found in the LICENSE file" – just that LICENSE file cannot be found, strange. Looking around, it seems [this one](https://chromium.googlesource.com/chromiumos/platform/vboot/+/0e5f54d79158f216edeb42bfe9c5cd6d35dc6e0d/LICENSE) seems to apply, which would make it BSD-3-Clause. (you might wish to place these details somewhere easy to find :wink:)

So I've added your module to [my Magisk repo](https://apt.izzysoft.de/magisk) now, thanks!

**Comment by anasfanani** [comment]
Wow, thankyou for the feedback. I will update my license, please check this my other module also.

https://github.com/anasfanani/Magisk-Tailscaled

**Comment by IzzySoft** [comment]
I am no lawyer, so I do not know and cannot tell which license takes the lead here. I only know BSD-3-Clause and MIT [go well together](https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/#bsd-3-clause-license-vs-the-mit-license) as they are both rather permissive. As you've kept your code under MIT, I'll keep it listed as MIT here as well. Those interested in using the code directly will have to visit your repo anyway, and then can find out for themselves.

With Tailscaled it's clear as both parts use BSD-3-Clause. Unfortunately, that ZIP is a bit large; I draw a size limit here around 30 MB, as I do with [my Android App repo](https://apt.izzysoft.de/fdroid) (both are running on limited personal space), which is why I skipped your Tailscaled module (it's almost twice that size).

**Comment by anasfanani** [comment]
@IzzySoft 

Woww... Thankyou for providing me fossa.com, I will learn to use correct license for my project.

> Unfortunately, that ZIP is a bit large.

I want separate the arch as discused [here](https://github.com/anasfanani/Magisk-Tailscaled/issues/1#issuecomment-1860713084), but currently i can't do this because I work on another project.

> both are running on limited personal space

Why using a personal space rather than github for placing modules/apks ?

**Comment by IzzySoft** [comment]
Glad I could help! And I'm always open for suggestions on modules & apps to add here.

And no, I don't like using proprietary resources. Nor do I want to feed my code to MS for their AI stuff – which is why I moved all my code out of here.
