### ISSUE TITLE
It won't work without ramdisk (recovery magisk)

### ISSUE THREAD

**Issue by Mattia2700** [anasfanani/magisk-autoboot#2]
I just tested it, and it makes sense it doesn't work if you load Magisk from recovery because ramdisk is missing. I opened this issue just to let you know, maybe this information can be added to the requirements

**Comment by anasfanani** [comment]
> load Magisk from recovery

Do you mean flash this module trough recovery ?
I have mention to Install the downloaded zip file using Magisk App/TWRP.

**Comment by Mattia2700** [comment]
No no, I mean that for some phones root access comes by patching recovery.img instead of boot.img (when ramdisk is not present in the phone to be rooted). After you flashed the custom AP, these types of phones has to be booted by pressing the recovery keybind (that does not mean entering the recovery, because to do that you have to do a further step), so Magisk is able to load everything and gives you root access. If you boot it normally, you wouldn't get root access.

 I installed your module from Magisk app, and the logs says it patches boot.img of course. The intent of this issue is to inform you that your module won't work on these types of phones, because the "patched image" from Magisk app is the recovery. So normally the phone starts with the boot and then eventually enters the recovery (I suppose), but the Magisk scope is limited to the recovery in this case, and consequently during the boot process, your module doesn't get loaded and the phone won't autostart.

Maybe this piece of information can be added to the requirements, to help others if you want, underlying it works only on phones with ramdisk (where boot.img has been patched from Magisk, not the recovery).

**Comment by anasfanani** [comment]
Thank you for the detailed information. I apologize for any misunderstanding, as I'm still learning. This is the first time I've heard that Magisk can also patch the recovery. I must have missed that part in the Magisk installation guide since I followed tutorials from a Telegram community. I appreciate your suggestion and will update the README.md accordingly.

**Comment by anasfanani** [comment]
https://github.com/anasfanani/magisk-autoboot/blob/fa3f4b7c13a4ebb8a0aae9ea7929ed72493eee7b/README.md?plain=1#L19

Updated, thankyou verry much.
