### ISSUE TITLE
开机卡fastboot

### ISSUE THREAD

**Issue by gzfa** [anasfanani/magisk-autoboot#5]
作者大佬你好，在小米6和k40上刷入Magisk-Autoboot-v1.0.0能正常使用，刷入v1.0.1的版本开机会卡fastboot，小米6安卓9，k40安卓11，都是twrp刷入Magisk-v25.2.zip获取的root

**Comment by anasfanani** [comment]
我对最新更新的实施很糟糕，对此我感到抱歉，至少您尝试了旧版本并取得了好消息。
当我有时间的时候我会修复它。

Wǒ duì zuìxīn gēngxīn de shíshī hěn zāogāo, duì cǐ wǒ gǎndào bàoqiàn, zhìshǎo nín chángshìle jiù bǎnběn bìng qǔdéle hǎo xiāoxī.
Dāng wǒ yǒu shíjiān de shíhòu wǒ huì xiūfù tā.

I have bad implementation on latest update, Im sorry for that, at least you try old version an worked its good news.
I will fix it when I have time to do.

**Comment by anasfanani** [comment]
Thankyou for reporting, I have fix and give better error handling on the script,

https://github.com/anasfanani/magisk-autoboot/releases/tag/v2.0.0

I'il close this issue, again, thankyou for your reporting.
